/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as NextRouteImport } from './routes/next'
import { Route as NewAlbumRouteImport } from './routes/new-album'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistIdRouteImport } from './routes/playlist.$id'
import { Route as MvIdRouteImport } from './routes/mv.$id'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoI18nRouteImport } from './routes/demo.i18n'
import { Route as DemoBetterAuthRouteImport } from './routes/demo/better-auth'
import { Route as DailySongsRouteImport } from './routes/daily.songs'
import { Route as ArtistIdRouteImport } from './routes/artist.$id'
import { Route as AlbumIdRouteImport } from './routes/album.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const NextRoute = NextRouteImport.update({
  id: '/next',
  path: '/next',
  getParentRoute: () => rootRouteImport,
} as any)
const NewAlbumRoute = NewAlbumRouteImport.update({
  id: '/new-album',
  path: '/new-album',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistIdRoute = PlaylistIdRouteImport.update({
  id: '/playlist/$id',
  path: '/playlist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const MvIdRoute = MvIdRouteImport.update({
  id: '/mv/$id',
  path: '/mv/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoI18nRoute = DemoI18nRouteImport.update({
  id: '/demo/i18n',
  path: '/demo/i18n',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoBetterAuthRoute = DemoBetterAuthRouteImport.update({
  id: '/demo/better-auth',
  path: '/demo/better-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DailySongsRoute = DailySongsRouteImport.update({
  id: '/daily/songs',
  path: '/daily/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistIdRoute = ArtistIdRouteImport.update({
  id: '/artist/$id',
  path: '/artist/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumIdRoute = AlbumIdRouteImport.update({
  id: '/album/$id',
  path: '/album/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/new-album': typeof NewAlbumRoute
  '/next': typeof NextRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/daily/songs': typeof DailySongsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/mv/$id': typeof MvIdRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/new-album': typeof NewAlbumRoute
  '/next': typeof NextRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/daily/songs': typeof DailySongsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/mv/$id': typeof MvIdRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/explore': typeof ExploreRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/new-album': typeof NewAlbumRoute
  '/next': typeof NextRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/album/$id': typeof AlbumIdRoute
  '/artist/$id': typeof ArtistIdRoute
  '/daily/songs': typeof DailySongsRoute
  '/demo/better-auth': typeof DemoBetterAuthRoute
  '/demo/i18n': typeof DemoI18nRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/mv/$id': typeof MvIdRoute
  '/playlist/$id': typeof PlaylistIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/explore'
    | '/library'
    | '/login'
    | '/new-album'
    | '/next'
    | '/search'
    | '/settings'
    | '/album/$id'
    | '/artist/$id'
    | '/daily/songs'
    | '/demo/better-auth'
    | '/demo/i18n'
    | '/demo/tanstack-query'
    | '/mv/$id'
    | '/playlist/$id'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/explore'
    | '/library'
    | '/login'
    | '/new-album'
    | '/next'
    | '/search'
    | '/settings'
    | '/album/$id'
    | '/artist/$id'
    | '/daily/songs'
    | '/demo/better-auth'
    | '/demo/i18n'
    | '/demo/tanstack-query'
    | '/mv/$id'
    | '/playlist/$id'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/explore'
    | '/library'
    | '/login'
    | '/new-album'
    | '/next'
    | '/search'
    | '/settings'
    | '/album/$id'
    | '/artist/$id'
    | '/daily/songs'
    | '/demo/better-auth'
    | '/demo/i18n'
    | '/demo/tanstack-query'
    | '/mv/$id'
    | '/playlist/$id'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExploreRoute: typeof ExploreRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  NewAlbumRoute: typeof NewAlbumRoute
  NextRoute: typeof NextRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  AlbumIdRoute: typeof AlbumIdRoute
  ArtistIdRoute: typeof ArtistIdRoute
  DailySongsRoute: typeof DailySongsRoute
  DemoBetterAuthRoute: typeof DemoBetterAuthRoute
  DemoI18nRoute: typeof DemoI18nRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  MvIdRoute: typeof MvIdRoute
  PlaylistIdRoute: typeof PlaylistIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/next': {
      id: '/next'
      path: '/next'
      fullPath: '/next'
      preLoaderRoute: typeof NextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-album': {
      id: '/new-album'
      path: '/new-album'
      fullPath: '/new-album'
      preLoaderRoute: typeof NewAlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlist/$id': {
      id: '/playlist/$id'
      path: '/playlist/$id'
      fullPath: '/playlist/$id'
      preLoaderRoute: typeof PlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mv/$id': {
      id: '/mv/$id'
      path: '/mv/$id'
      fullPath: '/mv/$id'
      preLoaderRoute: typeof MvIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/i18n': {
      id: '/demo/i18n'
      path: '/demo/i18n'
      fullPath: '/demo/i18n'
      preLoaderRoute: typeof DemoI18nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/better-auth': {
      id: '/demo/better-auth'
      path: '/demo/better-auth'
      fullPath: '/demo/better-auth'
      preLoaderRoute: typeof DemoBetterAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily/songs': {
      id: '/daily/songs'
      path: '/daily/songs'
      fullPath: '/daily/songs'
      preLoaderRoute: typeof DailySongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artist/$id': {
      id: '/artist/$id'
      path: '/artist/$id'
      fullPath: '/artist/$id'
      preLoaderRoute: typeof ArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$id': {
      id: '/album/$id'
      path: '/album/$id'
      fullPath: '/album/$id'
      preLoaderRoute: typeof AlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExploreRoute: ExploreRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  NewAlbumRoute: NewAlbumRoute,
  NextRoute: NextRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  AlbumIdRoute: AlbumIdRoute,
  ArtistIdRoute: ArtistIdRoute,
  DailySongsRoute: DailySongsRoute,
  DemoBetterAuthRoute: DemoBetterAuthRoute,
  DemoI18nRoute: DemoI18nRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  MvIdRoute: MvIdRoute,
  PlaylistIdRoute: PlaylistIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
